In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential # init NN
from keras.layers import Dense, Dropout # create layers in ANN
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

## Getting Dataset

In [74]:
dataset = pd.read_csv('https://raw.githubusercontent.com/lanceeeaton/ANN_Churn_Modeling/master/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

## Checking for missing values

In [75]:
dataset.isnull().values.any()

False

## Defining independent variables X and dependent variable y

In [0]:
X = dataset.iloc[:,3:13]
y = dataset.iloc[:,-1].values

## Looking at X

In [84]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

## Looking at y

In [85]:
y[:5]

array([1, 0, 1, 0, 0])

## Encoding Categorical Vars, Making Dummy Vars and avoiding Dummy var Trap

In [0]:
X = pd.get_dummies(X, columns = ['Geography','Gender'])
X = X.drop(columns=['Geography_Spain', 'Gender_Male'])

## Looking at X again

In [87]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   

   Gender_Female  
0              1  
1              1  
2              1  
3              1  
4              1

##Converting to float to avoid warning

In [0]:
X = X.astype(float)

## Spliting

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [0]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

## Building our ANN

In [0]:
def build_classifier():
  """Builds ANN classifier with 11 input neurons, 2 hidden layers each with 7 neurons (rectifier function) and 1 output neuron (sigmoid function)"""
  classifier = Sequential()
  classifier.add(Dense(activation ='relu', input_dim = 11, units = 7, kernel_initializer ='uniform')) # units = 2/3(num input nodes + num output nodes)
  classifier.add(Dense(activation ='relu', units = 7, kernel_initializer ='uniform')) # 2nd hidden layer
  classifier.add(Dense(activation ='sigmoid', units = 1, kernel_initializer ='uniform')) # out layer
  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy']) # telling it to use stochastic gradient descent, and cross-entropy loss for a binary output
  return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 32, epochs = 100)

## Getting our  accuracy scores, for 10 Fold Cross Validation

In [92]:
scores = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
scores

array([0.855  , 0.8375 , 0.8775 , 0.84   , 0.85375, 0.83625, 0.8325 ,
       0.85375, 0.8125 , 0.8425 ])

## The average accuracy score

In [93]:
scores.mean()

0.8441249999999998

## Training our classifier, and predicting on test set

In [94]:
classifier.fit(X_train, y_train)
y_pred_prob = classifier.predict(X_test)
y_pred = (y_pred_prob > 0.5)

Epoch 1/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.5565 - acc: 0.7953
Epoch 2/100
8000/8000 [==============================] - 0s 35us/step - loss: 0.4346 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4275 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4218 - acc: 0.8006
Epoch 5/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4170 - acc: 0.8257
Epoch 6/100
8000/8000 [==============================] - 0s 35us/step - loss: 0.4127 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 0s 35us/step - loss: 0.4102 - acc: 0.8316
Epoch 8/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4079 - acc: 0.8329
Epoch 9/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4062 - acc: 0.8345
Epoch 10/100
8000/8000 [==============================] - 0s 34us/step - loss: 0.4046 - acc: 0.8342
Epoch 11/

## Making a confusion matrix to better understand results

In [95]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1542,   53],
       [ 269,  136]])

## Seeing our actual accuracy

In [96]:
accuracy = (cm[0][0] + cm[1][1])/ len(y_pred)
accuracy

0.839

## Defining a new customer

In [0]:
new_customer = [[600,40, 3, 60000, 2, 1, 1, 50000,1,0,0]]

## Scaling the customer's data

In [0]:
new_customer = standard_scaler.transform(new_customer)

## Making prediction on our new customer

In [99]:
new_customer_pred_prob = classifier.predict(new_customer)
new_customer_pred = (new_customer_pred_prob > 0.5)
new_customer_pred

array([[False]])

This is an exercise that correponds with the Deep Learning A-Z course on Udemy.