In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential # init NN
from keras.layers import Dense, Dropout # create layers in ANN
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [0]:
dataset = pd.read_csv('https://raw.githubusercontent.com/lanceeeaton/ANN_Churn_Modeling/master/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [0]:
dataset.isnull().values.any()

False

In [0]:
X = dataset.iloc[:,3:13]
y = dataset.iloc[:,-1].values

In [0]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [0]:
y[:5]

array([1, 0, 1, 0, 0])

Encoding Categorical Vars, Making Dummy Vars and avoiding Dummy var Trap

In [0]:
X = pd.get_dummies(X, columns = ['Geography','Gender'])
X = X.drop(columns=['Geography_Spain', 'Gender_Male'])

In [0]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   

   Gender_Female  
0              1  
1              1  
2              1  
3              1  
4              1

Converting to float to avoid warning

In [0]:
X = X.astype(float)

Spliting

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [0]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [0]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(activation ='relu', input_dim = 11, units = 7, kernel_initializer ='uniform')) # units = 2/3(num input nodes + num output nodes)
  classifier.add(Dense(activation ='relu', units = 7, kernel_initializer ='uniform')) # 2nd hidden layer
  classifier.add(Dense(activation ='sigmoid', units = 1, kernel_initializer ='uniform')) # out layer
  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy']) # telling it to use stochastic gradient descent, and cross-entropy loss for a binary output
  return classifier

In [0]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 32, epochs = 100)
scores = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)

In [0]:
scores

array([0.83875, 0.83375, 0.87875, 0.83   , 0.85375, 0.8325 , 0.835  ,
       0.845  , 0.80875, 0.84375])

In [0]:
scores.mean()

0.8399999999999999

In [0]:
y_pred_prob = classifier.predict(X_test)
y_pred = (y_pred_prob > 0.5)

In [0]:
cm = confusion_matrix(y_test, y_pred)

In [0]:
cm

array([[1524,   71],
       [ 204,  201]])

In [0]:
accuracy = (cm[0][0] + cm[1][1])/ len(y_pred)
accuracy

0.8625

In [0]:
new_customer = [[600,40, 3, 60000, 2, 1, 1, 50000,1,0,0]]

In [0]:
new_customer = standard_scaler.transform(new_customer)

In [0]:
new_customer_pred_prob = classifier.predict(new_customer)
new_customer_pred = (new_customer_pred_prob > 0.5)
new_customer_pred

array([[False]])

This is an exercise that correponds with the Deep Learning A-Z course on Udemy.